env:
  experiment_id: "vd_finetune_mydata"
  log_root_dir: "./logs" 
  log_dir: "./logs/vd_finetune_mydata"
  gpu_count: 1
  nodes: 1
  node_rank: 0
  dist_backend: "nccl"
  dist_url: "tcp://127.0.0.1:11233"
  cuda: true
  rnd_seed: 42

model: MODEL(vd_text_to_image)
model_pretrain_path: "/root/vd/pretrained/vd-four-flow-v1-0.pth"

train:
  main:  "lib.utils.train"
  stage: "lib.text_to_image_train_stage.TextToImageTrainStage"

  batch_size: 1
  batch_size_per_gpu: 1
  dataset_num_workers: 1
  dataset_num_workers_per_gpu: 1

  skip_partial_batch: false

  step_type: "iter"
  step_num: 50000

  log_every: 10
  eval_every: 1000
  eval_start: 1000
  ckpt_every: 10000

  save_init_model: false
  gradacc_every: 10
  
  max_txt_len: 77

  vd:
    x_type: "image"
    x_vae:  "image"

    c_type: "text" 
    c_ctx:  "text"

  dataset:
    symbol: "my_vd_dataset"
    name:   "my_vd_dataset"
    
    root: "/root/data/laion-subset/train"
    meta_file: "meta.jsonl"

    image_size: 256
    sampler: "default_train"

  optimizer:
    type: "sgd"
    args:
      lr: 1.0e-5
      momentum: 0.9
      weight_decay: 0.0

  scheduler: null

eval:
  main: "lib.utils.eval"
  stage: "lib.text_to_image_eval_stage.TextToImageEvalStage"
  batch_size: 1
  batch_size_per_gpu: 1
  dataset_num_workers: 1
  dataset_num_workers_per_gpu: 1

  log_display: 100
  log_dir: "./logs/text_to_image_finetune/eval"
  output_result: false

  evaluator:
    name: "avg_loss"
    args:
      pass

  skip_partial_batch: false
  dataset:
    symbol: "my_vd_dataset"
    name:   "my_vd_dataset"

    root: "/root/data/laion-subset/eval"
    meta_file: "meta.jsonl"

    image_size: 256
    sampler: "default_val"
    
